{
 "title": "WeatherFlow - Today So Far",
 "description": "A live details dashboard for WeatherFlow's TEMPEST Weather System using collected raw JSON logs stored in Grafana Loki.",
 "tags": [
  "weatherflow",
  "loki"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Observations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "Temperature",
     "expr": "avg by (obs_Air_Temperature) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature |  __error__=\"\" [$__interval])) * 9/5 + 32",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Temperature",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "Humidity",
     "expr": "avg by (obs_Relative_Humidity) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Relative_Humidity=\"obs[0][8]\" | unwrap obs_Relative_Humidity |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Relative Humidity",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Station Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "alias": "Pressure",
     "expr": "avg by (obs_Station_Pressure) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Station_Pressure=\"obs[0][6]\" | unwrap obs_Station_Pressure |  __error__=\"\"[$__interval])) * .0295301",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Station Pressure",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "station_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* .0295301" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accumulated Rain",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "alias": "Accumulated",
     "expr": "avg by (obs_Precip_Accumilated) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Precip_Accumilated=\"obs[0][12]\" | unwrap obs_Precip_Accumilated  |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Accumulated Rain",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "rain_accumulated" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Solar Radiation",
     "expr": "avg by (obs_Solar_Radiation) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Solar_Radiation=\"obs[0][11]\" | unwrap obs_Solar_Radiation |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Solar Radiation",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "solar_radiation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "alias": "Illuminance",
     "expr": "avg by (obs_Illuminance) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Illuminance=\"obs[0][9]\" | unwrap obs_Illuminance |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Illuminance",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "illuminance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "UV",
     "expr": "avg by (obs_UV) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_UV=\"obs[0][10]\" | unwrap obs_UV |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "UV",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "uv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lightening Strike",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Average Distance",
     "expr": "avg by (obs_Lightning_Strike_Avg_Distance) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Lightning_Strike_Avg_Distance=\"obs[0][14]\" | unwrap obs_Lightning_Strike_Avg_Distance |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Average Distance",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "lightning_strike_avg_distance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Count",
     "expr": "avg by (obs_Lightning_Strike_Count) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Lightning_Strike_Count=\"obs[0][15]\" | unwrap obs_Lightning_Strike_Count |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Count",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "lightning_strike_avg_distance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Direction (Rapid)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ob_Wind_Direction) (avg_over_time({app=\"weatherflow\"} | json | type=\"rapid_wind\" |json | json ob_Wind_Direction=\"ob[2]\" | unwrap ob_Wind_Direction |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "wind_direction" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed (Rapid / 60 Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "alias": "Rapid Wind",
     "expr": "avg by (ob_Wind_Speed) (avg_over_time({app=\"weatherflow\"} | json | type=\"rapid_wind\" |json | json ob_Wind_Speed=\"ob[1]\" | unwrap ob_Wind_Speed |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "legendFormat": "Wind Speed",
     "measurement": "wf/rapid_wind",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "alias": "Wind Average",
     "expr": "avg by (obs_Wind_Lull) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Wind_Lull=\"obs[0][1]\" | unwrap obs_Wind_Lull |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Lull",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "wind_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wind Gust",
     "expr": "avg by (obs_Wind_Avg) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Wind_Avg=\"obs[0][2]\" | unwrap obs_Wind_Avg |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Average",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "wind_gust" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Wind Lull",
     "expr": "avg by (obs_Wind_Gust) (avg_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Wind_Gust=\"obs[0][3]\" | unwrap obs_Wind_Gust |  __error__=\"\" [$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Gust",
     "measurement": "wf/obs_st",
     "select": [
      [
       { "params": [ "wind_lull" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}