{
 "title": "WeatherFlow - Device Details",
 "description": "A details dashboard for WeatherFlow's TEMPEST Weather System using collected raw JSON logs stored in Grafana Loki.",
 "tags": [
  "weatherflow",
  "loki"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Hub",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(1,sum by (serial_number) (count_over_time({app=\"weatherflow\"} | json | type=\"hub_status\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{serial_number}}"
    }
   ]
  },
  {
   "title": "Status - Hub",
   "type": "table",
   "gridPos": { "h": 3, "w": 17, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json radio_stats_Version=\"radio_stats[0]\" | unwrap radio_stats_Version | __error__=\"\" [1m]))",
     "legendFormat": "Radio Version"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json radio_stats_Reboot_Count=\"radio_stats[1]\" | unwrap radio_stats_Reboot_Count | __error__=\"\" [1m]))",
     "legendFormat": "Reboot Count"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json radio_stats_I2C_Bus_Error_Count=\"radio_stats[2]\" | unwrap radio_stats_I2C_Bus_Error_Count | __error__=\"\" [1m]))",
     "legendFormat": "I2C Bus Count Error"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json radio_stats_Radio_Status=\"radio_stats[3]\" | unwrap radio_stats_Radio_Status | __error__=\"\" [1m]))",
     "legendFormat": "Radio Status"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json radio_stats_Radio_Network_ID=\"radio_stats[4]\" | unwrap radio_stats_Radio_Network_ID | __error__=\"\" [1m]))",
     "legendFormat": "Network ID"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json | unwrap firmware_revision | __error__=\"\" [1m]))",
     "legendFormat": "Firmware Version"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json | unwrap uptime | __error__=\"\" [1m]))",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json | unwrap rssi | __error__=\"\" [1m]))",
     "legendFormat": "RSSI"
    }
   ]
  },
  {
   "title": "Sensor Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum by (sensor_status) (count_over_time({app=\"weatherflow\"} | json | type=\"device_status\" |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{sensor_status}}"
    }
   ]
  },
  {
   "title": "Status - Tempest",
   "type": "table",
   "gridPos": { "h": 3, "w": 17, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap firmware_revision | __error__=\"\" [1m]))",
     "legendFormat": "Firmware Version"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap hub_rssi | __error__=\"\" [1m]))",
     "legendFormat": "Hub RSSI"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap rssi | __error__=\"\" [1m]))",
     "legendFormat": "RSSI"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap uptime | __error__=\"\" [1m]))",
     "legendFormat": "Uptime"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap voltage | __error__=\"\" [1m]))",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"hub_status\" | json | unwrap rssi | __error__=\"\" [$__interval]))",
     "legendFormat": "Hub"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap hub_rssi | __error__=\"\" [$__interval]))",
     "legendFormat": "WeatherFlow - Hub"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap rssi | __error__=\"\" [$__interval]))",
     "legendFormat": "WeatherFlow"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"device_status\" | json | unwrap voltage | __error__=\"\" [$__interval]))",
     "legendFormat": "Voltage"
    }
   ]
  }
 ]
}