{
 "title": "WeatherFlow - Overview",
 "description": "An overview dashboard for WeatherFlow's Weather Systems using collected raw JSON logs stored in Grafana Loki.",
 "tags": [
  "weatherflow",
  "loki"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Group",
    "label": "Group By",
    "query": "7d,2d,1d,12h,6h,4h,2h,1h,30m,15m,10m,5m,2m,1m,30s"
   }
  ]
 },
 "panels": [
  {
   "title": "Air Temperature (Last 24 Hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [1m])) * 9/5 + 32"
    },
    {
     "expr": "avg(avg_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [1m])) * 9/5 + 32"
    }
   ]
  },
  {
   "title": "Today's High",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32"
    }
   ]
  },
  {
   "title": "Today's Low",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Air Temperature (Last 7 Days)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Air Temperature (Last 7 Days)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Air_Temperature=\"obs[0][2]\" | unwrap obs_Air_Temperature | __error__=\"\" [$__interval])) * 9/5 + 32",
     "legendFormat": "Low"
    }
   ]
  },
  { "title": "Measurements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Relative_Humidity=\"obs[0][8]\" | unwrap obs_Relative_Humidity | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Relative_Humidity=\"obs[0][8]\" | unwrap obs_Relative_Humidity | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Relative_Humidity=\"obs[0][3]\" | unwrap obs_Relative_Humidity | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Relative_Humidity=\"obs[0][3]\" | unwrap obs_Relative_Humidity | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Station Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Station_Pressure=\"obs[0][6]\" | unwrap obs_Station_Pressure | __error__=\"\" [$__interval])) * .0295301",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Station_Pressure=\"obs[0][6]\" | unwrap obs_Station_Pressure | __error__=\"\" [$__interval])) * .0295301",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Station_Pressure=\"obs[0][1]\" | unwrap obs_Station_Pressure | __error__=\"\" [$__interval])) * .0295301",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Station_Pressure=\"obs[0][1]\" | unwrap obs_Station_Pressure | __error__=\"\" [$__interval])) * .0295301",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Wind Gusts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Wind_Gust=\"obs[0][3]\" | unwrap obs_Wind_Gust | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Wind_Gust=\"obs[0][3]\" | unwrap obs_Wind_Gust | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Wind_Gust=\"obs[0][6]\" | unwrap obs_Wind_Gust | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_air\" | json obs_Wind_Gust=\"obs[0][6]\" | unwrap obs_Wind_Gust | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Illuminance=\"obs[0][9]\" | unwrap obs_Illuminance | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Illuminance=\"obs[0][9]\" | unwrap obs_Illuminance | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_sky\" | json obs_Illuminance=\"obs[0][1]\" | unwrap obs_Illuminance | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_sky\" | json obs_Illuminance=\"obs[0][1]\" | unwrap obs_Illuminance | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Solar_Radiation=\"obs[0][11]\" | unwrap obs_Solar_Radiation | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_Solar_Radiation=\"obs[0][11]\" | unwrap obs_Solar_Radiation | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_sky\" | json obs_Solar_Radiation=\"obs[0][10]\" | unwrap obs_Solar_Radiation | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_sky\" | json obs_Solar_Radiation=\"obs[0][10]\" | unwrap obs_Solar_Radiation | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_UV=\"obs[0][10]\" | unwrap obs_UV | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_st\" | json obs_UV=\"obs[0][10]\" | unwrap obs_UV | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    },
    {
     "expr": "max(max_over_time({app=\"weatherflow\"} |= \"obs_sky\" | json obs_UV=\"obs[0][2]\" | unwrap obs_UV | __error__=\"\" [$__interval]))",
     "legendFormat": "High"
    },
    {
     "expr": "min(min_over_time({app=\"weatherflow\"} |= \"obs_sky\" | json obs_UV=\"obs[0][2]\" | unwrap obs_UV | __error__=\"\" [$__interval]))",
     "legendFormat": "Low"
    }
   ]
  }
 ]
}